apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-it-web
  namespace: acme-it
labels:
  app: acme-it-web
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: acme-it-web
  template:
    metadata:
      labels:
        app: acme-it-web
    spec:
      containers:
        - name: acme-it-web
          image: IMAGE_PLACEHOLDER   # <-- replaced by the workflow
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
