name: Build and Deploy to AKS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Workflow-wide permissions (so OIDC works in every job)
permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ${{ vars.ACR_LOGIN_SERVER }} # e.g. myregistry.azurecr.io
  IMAGE_NAME: acme-it-web
  AKS_NAMESPACE: acme-it

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR (token-based, no DinD)
        run: |
          TOKEN=$(az acr login -n "${{ vars.ACR_NAME }}" --expose-token --output tsv --query accessToken)
          echo "$TOKEN" | docker login $REGISTRY -u 00000000-0000-0000-0000-000000000000 --password-stdin

      - name: Build and push image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} -t $REGISTRY/$IMAGE_NAME:latest .
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AKS_CLUSTER_NAME }}

      - name: Create namespace if not exists
        run: |
          kubectl get ns $AKS_NAMESPACE || kubectl create ns $AKS_NAMESPACE

      - name: Update image in deployment manifest
        run: |
          sed -i 's#ghcr.io/OWNER/REPO/acme-it-web:latest#'"$REGISTRY/$IMAGE_NAME:${{ github.sha }}"'#' k8s/deployment.yaml

      - name: Apply manifests
        run: |
          # namespace.yaml omitted since we create it above if missing
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          if [ -f k8s/ingress.yaml ]; then kubectl apply -f k8s/ingress.yaml; fi

      -  name: Wait for rollout (up to 10m)
        run: |
          # give kubelet a head start to pull image
          sleep 20
          kubectl -n $AKS_NAMESPACE rollout status deploy/acme-it-web --timeout=10m
